service: serverless-rest-api
frameworkVersion: '>=3.22.0'

# plugins:
#   - serverless-offline

provider:
  name: aws
  architecture: x86_64
  runtime: go1.x
  region: eu-central-1
  stage: local
functions:
  api:
    handler: bin/main
    events:
      - http:
          path: /ping
          method: GET
package:
  patterns:
    - '!*/**'
    - ./bin/main

# package:
#   include:
#     - ./bin/main    

