name: Environment Variable Example

on:
    workflow_dispatch:
        
        inputs:
            my_variable:
                description: Name of the environment
                required: true


jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      MY_VARIABLE: ${{ github.event.inputs.my_variable }}

    steps:
      - name: Print Variable
        run: echo "Value of MY_VARIABLE is $MY_VARIABLE"
