name: Go-Rest-Cli CI

on:
  push:
    branches: [ "main", "*" ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [18.x]
          go: ['1.21']
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - run: go version 

    - name: Build
      run: env GOOS=linux go build -ldflags="-s -w" -o bin/main main.go

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: serverless deploy
      uses: serverless/github-action@v3.2
      with:
       args: deploy --help
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
