name: Go-Rest-Cli CI

on:
  push:
    branches: [ "main", "*" ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [18.x]
          go: ['1.21.x']
    # outputs:
    #     stage: ${{ steps.stage_name.outputs.stage }}
    steps:
    - uses: actions/checkout@v4

    - name: Stage Name
      id: stage_name
      run: |
        branch_name=$(git rev-parse --abbrev-ref HEAD)
        stage="dev"
         if [[ "$branch_name" == "main" ]]; then
          stage="prod"
         fi
         echo $stage

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - run: |
        go version

    - name: Build
      run: env GOOS=linux go build -ldflags="-s -w" -o bin/main main.go

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: serverless deploy to prod
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: serverless/github-action@v3.2
      with:
       args: print
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: serverless deploy to dev
      if: ${{ github.ref != 'refs/heads/main' }}
      uses: serverless/github-action@v3.2
      with:
       args: print
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
