name: serverless framework pipeline

on:
 push:
  branches: ['main', '*']
 pull_request:

jobs:
    Build:
      runs-on: ubuntu-latest
      steps:
      - name:
        run: |
            echo "Test Pipeline"
          
